listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
}

http_api {
    enabled         on;
    listen          1985;
}

vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_publish      http://api:4001/api/webhooks/rtmp/on-publish;
        on_unpublish    http://api:4001/api/webhooks/rtmp/on-unpublish;
        on_connect      http://api:4001/api/webhooks/rtmp/on-connect;
        on_close        http://api:4001/api/webhooks/rtmp/on-close;
    }

    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    2;
        hls_window      10;
    }
}
